--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KenCir/PMMPLibFormAPI
build-by-default: true
branches:
- master
projects:
  LibFormAPI:
    path: ""
    type: library
    model: virion
...
